name = "cloudflare-internship"
type = "javascript"
account_id = "1806d34a9fb55174f9d4b88cf53ff8bf"
workers_dev = true


[env.production]
route = "http://jhnatek.codes/*"
zone_id = "be1a46441a869865fd6f24a8a59a6e12"
